# GENERATED by tools/cluster-factory from config/clusters.yaml — DO NOT EDIT.
# Remote state for the @@ENV@@-@@PURPOSE@@ cluster. The bucket is supplied at init
# (account-specific, not committed):
#   terraform init -backend-config="bucket=<project>-tf-state"
terraform {
  backend "gcs" {
    prefix = "env/@@ENV@@/@@PURPOSE@@"
  }
}
