# GENERATED by tools/cluster-factory from config/clusters.yaml — DO NOT EDIT.
# Account- and identity-specific inputs for the dev-mgmt cluster root.
# The cluster's shape (sizing, ingress, DNS) lives in main.tf, also generated.
# These values are account-specific: supplied via terraform.tfvars (git-ignored)
# or TF_VAR_* in CI, never committed.

variable "project_id" {
  description = "The target Google Cloud project."
  type        = string
}

variable "region" {
  description = "Region for the regional cluster."
  type        = string
  default     = "us-central1"
}

variable "state_bucket" {
  description = "Cloud Storage bucket holding the foundation's remote state (<project>-tf-state)."
  type        = string
}

variable "operator_members" {
  description = "SRE operator identities (IAM member strings) granted Connect Gateway + cluster-admin RBAC, e.g. [\"group:sre@aifabrik.com\"]."
  type        = list(string)
}

variable "automation_member" {
  description = "CI automation identity that applies in-cluster resources via the gateway, e.g. \"serviceAccount:auto@project.iam.gserviceaccount.com\"."
  type        = string
}
