# dev-fop — generated cluster root. DO NOT EDIT BY HAND.
# Generated by tools/cluster-factory from config/clusters.yaml: change the
# cluster's entry there and re-run bootstrap/add-cluster-purpose.sh. Thin by
# design — reads the per-project foundation's outputs and calls cluster-stack
# with this cluster's coordinates, sizing, and ingress from the registry.

data "terraform_remote_state" "foundation" {
  backend = "gcs"
  config = {
    bucket = var.state_bucket
    prefix = "env/dev/foundation"
  }
}

module "stack" {
  source = "../../../modules/cluster-stack"

  project_id  = var.project_id
  region      = var.region
  environment = "dev"
  purpose     = "fop"

  # From the per-project foundation (shared by every purpose in the project).
  kms_key_id                 = data.terraform_remote_state.foundation.outputs.kms_crypto_key_id
  node_service_account_email = data.terraform_remote_state.foundation.outputs.node_service_account_email

  # Cluster shape (from the registry).
  cas_tier             = "DEVOPS"
  general_machine_type = "e2-medium"
  general_autoscaling = {
    min_per_zone = 1
    max_per_zone = 2
  }
  release_channel = "REGULAR"
  maintenance_recurring_window = {
    start_time = "2026-01-03T09:00:00Z"
    end_time   = "2026-01-03T17:00:00Z"
    recurrence = "FREQ=WEEKLY;BYDAY=SA,SU"
  }
  deletion_protection = false
  enable_cloud_nat    = true

  operator_members  = var.operator_members
  automation_member = var.automation_member

  # Ingress: public external + private internal (ADR-0005); internal names
  # resolve via the per-environment private zone (ADR-0006).
  external_hostnames   = ["app.dev.arthos.app", "hello.dev.arthos.app", "sd1.dev.arthos.app", "sd2.dev.arthos.app", "sd3.dev.arthos.app"]
  internal_hostnames   = ["hello.dev.aifabrik.com", "tools.dev.aifabrik.com"]
  internal_zone_domain = "dev.aifabrik.com"
  manage_public_dns    = true
  public_zone_domain   = "dev.arthos.app"
}
