"""Render normalized Terraform roots from the cluster registry (ADR-0009).

Each active cluster becomes a thin root under ``terraform/envs/<env>/<purpose>/``
that calls the ``cluster-stack`` module. Roots are **normalized** (uniform across
purposes) and committed; the ``main.tf`` carries the per-cluster module inputs
from the registry, the other files are token-substituted templates. Migrating an
existing cluster regenerates its source — the safety proof that nothing changes is
a ``terraform plan`` no-op (the module inputs are unchanged), not byte-identical
source.

Output is run through ``terraform fmt`` so the committed roots are canonically
formatted and regeneration is idempotent. ``generate(check=True)`` renders to a
temp tree and diffs against the committed roots without touching them — the CI
drift guard.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from cluster_factory.registry import active_clusters, effective_config, load
from cluster_factory.workflows import update_workflows

# Files produced by pure token substitution from templates/root/. main.tf is
# built programmatically (it carries the per-cluster module inputs).
_STATIC_FILES = (
    "backend.tf",
    "providers.tf",
    "versions.tf",
    "variables.tf",
    "outputs.tf",
    "terraform.tfvars.example",
)
_TEMPLATE_DIR = Path(__file__).resolve().parent / "templates" / "root"
# Canonical provider lock, copied verbatim into every root so all clusters pin
# the same provider versions with hashes for every CI/dev platform. Updating
# providers = update this one file (terraform providers lock) + regenerate.
_LOCK_TEMPLATE = Path(__file__).resolve().parent / "templates" / "terraform.lock.hcl"


def _hcl(value: Any) -> str:
    """Format a Python value as an HCL literal (bool/number/string/list).

    Strings are fully escaped for a double-quoted HCL literal: backslash and quote
    first, then the control characters terraform requires as ``\\n``/``\\r``/``\\t``,
    then the template-interpolation openers ``${``/``%{`` doubled to ``$${``/``%%{``
    so a registry value is always a literal, never live interpolation. Order
    matters — backslash is escaped before the others so their added backslashes are
    not double-escaped.
    """
    if isinstance(value, bool):  # before int — bool is an int subclass
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        s = value.replace("\\", "\\\\").replace('"', '\\"')
        s = s.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
        s = s.replace("${", "$${").replace("%{", "%%{")
        return '"' + s + '"'
    if isinstance(value, list):
        return "[" + ", ".join(_hcl(v) for v in value) + "]"
    raise TypeError(f"cannot render HCL for {type(value).__name__}: {value!r}")


def _render_main(cfg: dict[str, Any]) -> str:
    """Build ``main.tf`` for one cluster from its effective config.

    Pinned (non-registry) inputs — project/region/identities, the foundation
    remote-state reads — are emitted as fixed expressions; everything else is an
    HCL literal from the registry. Indentation is loose; ``terraform fmt`` aligns
    the ``=`` columns afterwards.
    """
    env, purpose = cfg["environment"], cfg["purpose"]
    out: list[str] = [
        f"# {env}-{purpose} — generated cluster root. DO NOT EDIT BY HAND.",
        "# Generated by tools/cluster-factory from config/clusters.yaml: change the",
        "# cluster's entry there and re-run bootstrap/add-cluster-purpose.sh. Thin by",
        "# design — reads the per-project foundation's outputs and calls cluster-stack",
        "# with this cluster's coordinates, sizing, and ingress from the registry.",
        "",
        'data "terraform_remote_state" "foundation" {',
        '  backend = "gcs"',
        "  config = {",
        "    bucket = var.state_bucket",
        f'    prefix = "env/{env}/foundation"',
        "  }",
        "}",
        "",
        'module "stack" {',
        '  source = "../../../modules/cluster-stack"',
        "",
        "  project_id  = var.project_id",
        "  region      = var.region",
        f'  environment = "{env}"',
        f'  purpose     = "{purpose}"',
        "",
        "  # From the per-project foundation (shared by every purpose in the project).",
        "  kms_key_id                 = data.terraform_remote_state.foundation.outputs.kms_crypto_key_id",
        "  node_service_account_email = data.terraform_remote_state.foundation.outputs.node_service_account_email",
        "",
        "  # Cluster shape (from the registry).",
        f'  cas_tier             = {_hcl(cfg["cas_tier"])}',
        f'  general_machine_type = {_hcl(cfg["general_machine_type"])}',
        "  general_autoscaling = {",
        f'    min_per_zone = {_hcl(cfg["general_autoscaling"]["min_per_zone"])}',
        f'    max_per_zone = {_hcl(cfg["general_autoscaling"]["max_per_zone"])}',
        "  }",
        f'  release_channel     = {_hcl(cfg["release_channel"])}',
    ]

    mw = cfg.get("maintenance_recurring_window")
    if mw:
        out += [
            "  maintenance_recurring_window = {",
            f'    start_time = {_hcl(mw["start_time"])}',
            f'    end_time   = {_hcl(mw["end_time"])}',
            f'    recurrence = {_hcl(mw["recurrence"])}',
            "  }",
        ]

    out += [
        f'  deletion_protection = {_hcl(cfg["deletion_protection"])}',
        f'  enable_cloud_nat    = {_hcl(cfg["enable_cloud_nat"])}',
        "",
        "  operator_members  = var.operator_members",
        "  automation_member = var.automation_member",
        "",
        "  # Ingress: public external + private internal (ADR-0005); internal names",
        "  # resolve via the per-environment private zone (ADR-0006).",
        f'  external_hostnames   = {_hcl(cfg["external_hostnames"])}',
        f'  internal_hostnames   = {_hcl(cfg["internal_hostnames"])}',
        f'  internal_zone_domain = {_hcl(cfg["internal_zone_domain"])}',
        f'  manage_public_dns    = {_hcl(cfg["manage_public_dns"])}',
        f'  public_zone_domain   = {_hcl(cfg["public_zone_domain"])}',
        "}",
    ]
    return "\n".join(out) + "\n"


def _render_static(name: str, env: str, purpose: str) -> str:
    """Token-substitute one static template file."""
    text = (_TEMPLATE_DIR / name).read_text(encoding="utf-8")
    return text.replace("@@ENV@@", env).replace("@@PURPOSE@@", purpose)


def _render_cluster_files(cfg: dict[str, Any]) -> dict[str, str]:
    """Return ``{filename: content}`` for one cluster's root (pre-fmt).

    Includes the canonical ``.terraform.lock.hcl`` so every root pins providers
    identically and a regenerate/``--check`` covers lock drift too.
    """
    env, purpose = cfg["environment"], cfg["purpose"]
    files = {name: _render_static(name, env, purpose) for name in _STATIC_FILES}
    files["main.tf"] = _render_main(cfg)
    files[".terraform.lock.hcl"] = _LOCK_TEMPLATE.read_text(encoding="utf-8")
    return files


class TerraformMissingError(RuntimeError):
    """``terraform`` is required (for fmt + canonical, verifiable output) but is
    not on PATH. Raised up front so the failure is loud, not a silent miss-format."""


# terraform reads *.tf and *.tf.json; a stray resource could hide in either. The
# generator owns the rendered set; any other matching file in a root is an orphan
# (hand-added, or left behind when a registry field stops emitting a file).
_TF_SOURCE_GLOBS = ("*.tf", "*.tf.json")


def _require_terraform() -> None:
    """Raise :class:`TerraformMissingError` unless terraform is on PATH."""
    if shutil.which("terraform") is None:
        raise TerraformMissingError(
            "terraform is not on PATH; it is required to format and verify "
            "generated roots — install it (see tools/cluster-factory/README.md)"
        )


def _terraform_fmt(directory: Path) -> None:
    """Canonically format the ``*.tf`` files in ``directory``.

    Assumes terraform is on PATH (callers guard with :func:`_require_terraform`).
    Raises ``subprocess.CalledProcessError`` if terraform rejects the input — the
    diagnostic is on ``exc.stderr`` for the caller to surface.
    """
    subprocess.run(
        ["terraform", "fmt", "-list=false", str(directory)],
        check=True,
        capture_output=True,
        text=True,
    )


def cluster_dir(repo_root: Path, env: str, purpose: str) -> Path:
    """Path to a cluster's Terraform root."""
    return Path(repo_root) / "terraform" / "envs" / env / purpose


def _render_to_temp(cfg: dict[str, Any], tmp: Path) -> dict[str, str]:
    """Render one cluster into ``tmp`` and ``terraform fmt`` it; return the final
    ``{name: content}`` (re-read post-fmt, so callers see canonical bytes)."""
    files = _render_cluster_files(cfg)
    for name, content in files.items():
        (tmp / name).write_text(content, encoding="utf-8")
    _terraform_fmt(tmp)
    return {name: (tmp / name).read_text(encoding="utf-8") for name in files}


def _orphan_source_files(target: Path, managed: set[str]) -> list[Path]:
    """``*.tf`` / ``*.tf.json`` files in ``target`` the generator does not manage."""
    if not target.is_dir():
        return []
    found: list[Path] = []
    for pattern in _TF_SOURCE_GLOBS:
        found += [p for p in sorted(target.glob(pattern)) if p.name not in managed]
    return found


def _orphan_roots(repo_root: Path, active: set[tuple[str, str]]) -> list[Path]:
    """Cluster root dirs under ``terraform/envs/<env>/<purpose>`` with no registry
    entry. Excludes ``foundation`` (a per-project root, not a cluster)."""
    envs_dir = repo_root / "terraform" / "envs"
    if not envs_dir.is_dir():
        return []
    orphans: list[Path] = []
    for env_dir in sorted(p for p in envs_dir.iterdir() if p.is_dir()):
        for root in sorted(p for p in env_dir.iterdir() if p.is_dir()):
            if root.name != "foundation" and (env_dir.name, root.name) not in active:
                orphans.append(root)
    return orphans


def generate(
    registry_path: str | Path,
    repo_root: str | Path,
    *,
    check: bool = False,
    dry_run: bool = False,
) -> list[str]:
    """Render every active cluster's root from the registry.

    Requires terraform on PATH (for fmt and canonical, verifiable output) — raises
    :class:`TerraformMissingError` otherwise, so a degraded run never passes
    silently.

    Write mode (default): each root is written **atomically** — rendered and
    ``terraform fmt``-ed in a temp dir first, so a fmt failure aborts before the
    committed root is touched — then synced, with orphan ``*.tf`` files pruned.
    Returns the relative paths of any orphan root *directories* (a cluster removed
    from the registry); those are **not** auto-deleted (destroy the cluster first).

    Check / dry-run: writes nothing and returns the drifted paths — managed files
    that differ, orphan source files, and orphan roots. ``check`` is the CI guard
    (a non-empty return means failure); ``dry_run`` is the same for humans.
    """
    _require_terraform()
    repo_root = Path(repo_root)
    data = load(registry_path)
    active = set(active_clusters(data))
    drift: list[str] = []

    for env, purpose in active_clusters(data):
        cfg = effective_config(data, env, purpose)
        target = cluster_dir(repo_root, env, purpose)
        managed = set(_render_cluster_files(cfg))

        with tempfile.TemporaryDirectory() as tmp:
            # fmt runs against the temp tree, before the committed root is touched.
            rendered = _render_to_temp(cfg, Path(tmp))

            if check or dry_run:
                for name, want in rendered.items():
                    committed = target / name
                    have = committed.read_text(encoding="utf-8") if committed.exists() else None
                    if want != have:
                        drift.append(str(committed.relative_to(repo_root)))
                drift += [str(p.relative_to(repo_root)) for p in _orphan_source_files(target, managed)]
                continue

            target.mkdir(parents=True, exist_ok=True)
            for name, content in rendered.items():
                (target / name).write_text(content, encoding="utf-8")
            for orphan in _orphan_source_files(target, managed):
                orphan.unlink()

    # Regenerate the pipeline's env/purpose enumerations from the same registry,
    # so the dispatch menus and the roots that exist can never disagree.
    if check or dry_run:
        drift += update_workflows(repo_root, data, check=True)
    else:
        update_workflows(repo_root, data, check=False)

    # Orphan root directories (registry entry removed) are flagged in every mode
    # and never auto-deleted — the operator destroys the cluster, then removes it.
    drift += [str(p.relative_to(repo_root)) for p in _orphan_roots(repo_root, active)]
    return drift
